MYSQL_USER=fiapdb
MYSQL_PASSWORD=fiapdb
MYSQL_DATABASE=fiapdb
SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/fiapdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC